export const data = [
  {
    fname: "محمد رضا",
    lname: "حیدری",
    age: "24",
    sickness: "فشار خون",
    doctor: "علی رضا عظیمی",
    id: "01",
  },
  {
    fname: "عاطفه",
    lname: "رضایی",
    age: "36",
    sickness: "سر درد",
    doctor: "علی مظاهری",
    id: "02",
  },
  {
    fname: "یاسین",
    lname: "شریفی",
    age: "12",
    sickness: "استرس",
    doctor: "سینا بختیاری",
    id: "03",
  },
  {
    fname: "محمد رضا",
    lname: "حیدری",
    age: "24",
    sickness: "فشار خون",
    doctor: "علی رضا عظیمی",
    id: "04",
  },
  {
    fname: "عاطفه",
    lname: "رضایی",
    age: "36",
    sickness: "سر درد",
    doctor: "علی مظاهری",
    id: "05",
  },
  {
    fname: "یاسین",
    lname: "شریفی",
    age: "12",
    sickness: "استرس",
    doctor: "سینا بختیاری",
    id: "06",
  },  {
    fname: "محمد رضا",
    lname: "حیدری",
    age: "24",
    sickness: "فشار خون",
    doctor: "علی رضا عظیمی",
    id: "07",
  },
  {
    fname: "عاطفه",
    lname: "رضایی",
    age: "36",
    sickness: "سر درد",
    doctor: "علی مظاهری",
    id: "08",
  },
  {
    fname: "یاسین",
    lname: "شریفی",
    age: "12",
    sickness: "استرس",
    doctor: "سینا بختیاری",
    id: "09",
  },  {
    fname: "محمد رضا",
    lname: "حیدری",
    age: "24",
    sickness: "فشار خون",
    doctor: "علی رضا عظیمی",
    id: "01",
  },
  {
    fname: "عاطفه",
    lname: "رضایی",
    age: "36",
    sickness: "سر درد",
    doctor: "علی مظاهری",
    id: "10",
  },
  {
    fname: "یاسین",
    lname: "شریفی",
    age: "12",
    sickness: "استرس",
    doctor: "سینا بختیاری",
    id: "11",
  },
];
